log_level: info
debug: 0
interval: 2
mysql:
  host: 127.0.0.1
  port: 3306
  username: root
  password: ""
  database: redisctl
influxdb:
  host: 10.1.201.42
  port: 8086
  username: root
  password: root
  database: redisctl
