log_level: info
debug: 0
interval: 10
mysql:
  host: 127.0.0.1
  port: 3306
  username: root
  password: ""
  db: redisctl
influxdb:
  host: 127.0.0.1
  port: 8086
  username: root
  password: root
  db: redisctl
